create database customer_behaviour;
use customer_behaviour;
select * from mytable limit 10;

# What is total revenue generated by male vs female customers
select gender,sum(purchase_amount) as revenue
from mytable group by gender;

#which customers used discount but still spend more than average purchase_amount?
select  customer_id,purchase_amount
from mytable
where discount_applied = "Yes" and purchase_amount>=(select avg(purchase_amount) from mytable);

#which are the top 5 products with highest average review rating?
select item_purchased ,avg(review_rating) as average_product_rating
from mytable
group by item_purchased
order by average_product_rating desc
limit 5;

#compare the average purchase amounts between standard and express shipping
select shipping_type,avg(purchase_amount)
from mytable
where shipping_type IN ("Standard","Express")
group by shipping_type;

#Compare average spend and total revenue between subscribers and non subscribers
select subscription_status,count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from mytable
group by subscription_status
order by total_revenue,avg_spend desc;

# which 5 products have the highest percentage of purchase with discount applied?
select item_purchased,
round(sum(case when discount_applied = "Yes" then 1 else 0 end)/count(*)*100,2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

# segments the customers into new,Returning and loyal based on their total
#number of previous purchase and show the counts of each segment
with customer_type as (
select customer_id,previous_purchases,
case
	when previous_purchases=1 then "New"
    when previous_purchases between 2 and 10 then "Returning"
    else "Loyal"
    end as customer_segment
    from mytable
    )
    select customer_segment,count(*) as "Number of Customers"
    from customer_type
    group by customer_segment;
    
    
    #what are top 3 most purchased products within each category
    with item_counts as (
    select category,item_purchased,
    count(customer_id) as total_orders,
    row_number() over (partition by category order by count(customer_id) desc ) as item_rank
    from mytable
    group by category,item_purchased)
    select item_rank,category,item_purchased,total_orders from item_counts where item_rank<=3;
    
    # customers who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
    select subscription_status,
    count(customer_id) as repeat_buyers
    from mytable
    where previous_purchases > 5
    group by subscription_status;
    
    # what is revenue contribution of each age groups
    select age-groups,
    sum(purchase_amount) as revenue
    from mytable
    group by age-groups
    order by revenue desc;